import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sf3d-artifact-args-')),reportPath=path.join(dir,'report.json');
const result=spawnSync(process.execPath,['--import','./tools/wgsl-raw-loader-register.mjs','tools/smoke_resident_dino.mjs','--through-full-model','--report',reportPath],{encoding:'utf8'});
assert.equal(result.status,1);assert.equal(fs.existsSync(reportPath),true,'argument failures retain a durable report before primary output');
const report=JSON.parse(fs.readFileSync(reportPath,'utf8'));
assert.equal(report.requested.throughFullModel,true,'requested full model must not silently become a partial encoder route');
assert.match(report.error.message,/full model requires complete backbone and postprocessor/);
assert.equal(report.cleanup.browser.status,'not-started');
assert.equal(typeof report.evidencePaths.glb,'string');
assert.equal(fs.existsSync(report.evidencePaths.glb),false);
const encoderReport=path.join(dir,'encoder-arguments.json');
const encoder=spawnSync(process.execPath,['tools/smoke_resident_dino.mjs','--report',encoderReport],{encoding:'utf8'});
assert.equal(encoder.status,1);
assert.equal(fs.existsSync(encoderReport),true,'new full consumer raw-WGSL imports must not break the existing encoder startup before its report');
assert.match(JSON.parse(fs.readFileSync(encoderReport,'utf8')).error.message,/explicit source/);
console.log('PASS full-model route selection fails loud before browser/device with durable argument-phase receipt at '+reportPath);
